SELECT NAME, COUNT(CLIENT_ID) as PROJECT_COUNT 
    FROM CLIENT, PROJECT
    WHERE CLIENT.ID = PROJECT.CLIENT_ID
    GROUP BY CLIENT.NAME 
        HAVING COUNT(CLIENT_ID) IN(
            SELECT count(CLIENT_ID)
            FROM PROJECT
            GROUP BY CLIENT_ID
            ORDER BY COUNT(CLIENT_ID) DESC
            LIMIT 1
);