SELECT CONCAT ('Project ',ID) as NAME,
DATEDIFF (month, START_DATE, FINISH_DATE) as MONTH_COUNT
FROM PROJECT
WHERE DATEDIFF(month, START_DATE, FINISH_DATE) =
SELECT MAX(DATEDIFF(month, START_DATE, FINISH_DATE)) FROM PROJECT;