SELECT CONCAT ('Project ',p.ID) as NAME,(SUM(w.salary)
 * DATEDIFF(month, START_DATE, FINISH_DATE)) as PRICE
FROM PROJECT p
INNER JOIN PROJECT_WORKER p_w on p.ID = p_w.PROJECT_ID
INNER JOIN WORKER w on p_w.WORKER_ID = w.ID
GROUP BY p.ID
ORDER BY PRICE DESC